# -*- coding: utf-8 -*-
"""01_random_forest_ndvi_baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WCa-_MI8UMXZoV4KX0Awb49xX7fg6Lb7
"""

import pandas as pd
from pathlib import Path

# --------------------------------------------------
# Load CSV file
# Works in both Google Colab and VS Code
# --------------------------------------------------

try:
    # This will work in Google Colab
    from google.colab import files
    uploaded = files.upload()
    file_name = list(uploaded.keys())[0]
    df = pd.read_csv(file_name)

except ImportError:
    # This will work in VS Code/local system
    data_path = Path("04_data/ai_training_dataset_ndvi_2019_2026.csv")

    if not data_path.exists():
        data_path = Path("../04_data/ai_training_dataset_ndvi_2019_2026.csv")

    df = pd.read_csv(data_path)

print("Dataset shape:", df.shape)
print("Columns:")
print(df.columns)

df.head()

# Keep only NDVI columns and label column
ndvi_columns = [col for col in df.columns if col.startswith("NDVI_")]

print("NDVI columns:", ndvi_columns)

# Create input X and output y
X = df[ndvi_columns]
y = df["label"]

# Remove missing values if any
data = pd.concat([X, y], axis=1).dropna()

X = data[ndvi_columns]
y = data["label"].astype(int)

print("Final dataset shape:", data.shape)
print("Class distribution:")
print(y.value_counts())

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

rf_all_years = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced"
)

rf_all_years.fit(X_train, y_train)

y_pred = rf_all_years.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall = recall_score(y_test, y_pred, zero_division=0)
f1 = f1_score(y_test, y_pred, zero_division=0)

print("All-years Accuracy:", accuracy)
print("All-years Precision:", precision)
print("All-years Recall:", recall)
print("All-years F1-score:", f1)

print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

# Leakage-check model: remove NDVI_2019 and NDVI_2026
# because these were directly used to create the labels

leakage_check_columns = [
    col for col in ndvi_columns
    if col not in ["NDVI_2019", "NDVI_2026"]
]

print("Columns used for leakage-check model:")
print(leakage_check_columns)

X_leakage_check = data[leakage_check_columns]
y_leakage_check = data["label"].astype(int)

X_train_lc, X_test_lc, y_train_lc, y_test_lc = train_test_split(
    X_leakage_check,
    y_leakage_check,
    test_size=0.2,
    random_state=42,
    stratify=y_leakage_check
)

rf_leakage_check = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced"
)

rf_leakage_check.fit(X_train_lc, y_train_lc)

y_pred_lc = rf_leakage_check.predict(X_test_lc)

accuracy_lc = accuracy_score(y_test_lc, y_pred_lc)
precision_lc = precision_score(y_test_lc, y_pred_lc, zero_division=0)
recall_lc = recall_score(y_test_lc, y_pred_lc, zero_division=0)
f1_lc = f1_score(y_test_lc, y_pred_lc, zero_division=0)

print("Leakage-check Accuracy:", accuracy_lc)
print("Leakage-check Precision:", precision_lc)
print("Leakage-check Recall:", recall_lc)
print("Leakage-check F1-score:", f1_lc)

print("\nClassification Report:")
print(classification_report(y_test_lc, y_pred_lc, zero_division=0))

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm_lc = confusion_matrix(y_test_lc, y_pred_lc)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_lc,
    display_labels=["Stable", "Changed"]
)

disp.plot()
plt.title("Random Forest Leakage-Check Confusion Matrix")
plt.savefig("random_forest_leakage_check_confusion_matrix.png", dpi=300, bbox_inches="tight")
plt.show()

importances_lc = rf_leakage_check.feature_importances_

feature_importance_lc_df = pd.DataFrame({
    "Feature": leakage_check_columns,
    "Importance": importances_lc
}).sort_values(by="Importance", ascending=False)

print(feature_importance_lc_df)

plt.figure(figsize=(8, 5))
plt.bar(feature_importance_lc_df["Feature"], feature_importance_lc_df["Importance"])
plt.xlabel("NDVI Year")
plt.ylabel("Importance")
plt.title("Random Forest Leakage-Check Feature Importance")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("random_forest_leakage_check_feature_importance.png", dpi=300, bbox_inches="tight")
plt.show()

metrics_comparison_df = pd.DataFrame({
    "Model": [
        "Random Forest using all NDVI years",
        "Random Forest without NDVI_2019 and NDVI_2026"
    ],
    "Accuracy": [accuracy, accuracy_lc],
    "Precision": [precision, precision_lc],
    "Recall": [recall, recall_lc],
    "F1_score": [f1, f1_lc]
})

metrics_comparison_df.to_csv("random_forest_metrics_comparison.csv", index=False)

metrics_comparison_df

import joblib

joblib.dump(rf_leakage_check, "random_forest_leakage_check_model.pkl")