# -*- coding: utf-8 -*-
"""02_check_vit_lstm_patch_centers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17NoCqbBsW6xUg1YhS4SgwcCILsn8Mqzx
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

print("Dataset shape:", df.shape)
print("Columns:")
print(df.columns)

df.head()

print("Missing values:")
print(df.isnull().sum())

print("\nClass distribution:")
print(df["label"].value_counts())

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))

for label_value, label_name in [(0, "Stable"), (1, "Changed")]:
    subset = df[df["label"] == label_value]
    plt.scatter(
        subset["longitude"],
        subset["latitude"],
        label=label_name,
        s=20
    )

plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.title("ViT-LSTM Patch Center Points")
plt.legend()
plt.grid(True)
plt.savefig("vit_lstm_patch_centers_preview.png", dpi=300, bbox_inches="tight")
plt.show()

