# -*- coding: utf-8 -*-
"""03_lstm_ndvi_temporal_baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gZ4Cm9mYupaYLbOymIjXVlloqR6f6bsc
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np

file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

print("Dataset shape:", df.shape)
print(df.columns)
df.head()

# Use only intermediate years to reduce direct label leakage
lstm_columns = [
    "NDVI_2020",
    "NDVI_2021",
    "NDVI_2022",
    "NDVI_2023",
    "NDVI_2024",
    "NDVI_2025"
]

data = df[lstm_columns + ["label"]].dropna()

X = data[lstm_columns].values
y = data["label"].astype(int).values

# LSTM input shape = samples, time steps, features
X = X.reshape(X.shape[0], X.shape[1], 1)

print("X shape:", X.shape)
print("y shape:", y.shape)

print("Class distribution:")
print(pd.Series(y).value_counts())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

model = Sequential([
    LSTM(32, input_shape=(X_train.shape[1], X_train.shape[2])),
    Dropout(0.3),
    Dense(16, activation="relu"),
    Dense(1, activation="sigmoid")
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=10,
    restore_best_weights=True
)

history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=100,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

y_prob = model.predict(X_test)
y_pred = (y_prob >= 0.5).astype(int).flatten()

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall = recall_score(y_test, y_pred, zero_division=0)
f1 = f1_score(y_test, y_pred, zero_division=0)

print("LSTM Accuracy:", accuracy)
print("LSTM Precision:", precision)
print("LSTM Recall:", recall)
print("LSTM F1-score:", f1)

print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Stable", "Changed"]
)

disp.plot()
plt.title("LSTM NDVI Temporal Baseline Confusion Matrix")
plt.savefig("lstm_ndvi_temporal_confusion_matrix.png", dpi=300, bbox_inches="tight")
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(history.history["accuracy"], label="Training Accuracy")
plt.plot(history.history["val_accuracy"], label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("LSTM NDVI Temporal Baseline Training Accuracy")
plt.legend()
plt.grid(True)
plt.savefig("lstm_ndvi_temporal_training_accuracy.png", dpi=300, bbox_inches="tight")
plt.show()

lstm_metrics_df = pd.DataFrame({
    "Model": ["LSTM NDVI temporal baseline"],
    "Accuracy": [accuracy],
    "Precision": [precision],
    "Recall": [recall],
    "F1_score": [f1]
})

lstm_metrics_df.to_csv("lstm_ndvi_temporal_metrics.csv", index=False)

lstm_metrics_df

files.download("lstm_ndvi_temporal_confusion_matrix.png")
files.download("lstm_ndvi_temporal_training_accuracy.png")
files.download("lstm_ndvi_temporal_metrics.csv")

