# -*- coding: utf-8 -*-
"""04_model_comparison_rf_vs_lstm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17db8qB4qyUCeERHqmLr5Ds5C5z2mVeUq
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt

# Read uploaded CSV files
csv_files = list(uploaded.keys())

print("Uploaded files:")
print(csv_files)

rf_file = [f for f in csv_files if "random_forest" in f][0]
lstm_file = [f for f in csv_files if "lstm" in f][0]

rf_df = pd.read_csv(rf_file)
lstm_df = pd.read_csv(lstm_file)

print("Random Forest Metrics:")
display(rf_df)

print("LSTM Metrics:")
display(lstm_df)

# Keep only the leakage-check Random Forest row
rf_leakage_df = rf_df[
    rf_df["Model"].str.contains("without NDVI_2019", case=False, na=False)
].copy()

# Combine Random Forest leakage-check with LSTM
comparison_df = pd.concat(
    [rf_leakage_df, lstm_df],
    ignore_index=True
)

comparison_df

comparison_df.to_csv("rf_vs_lstm_model_comparison.csv", index=False)

comparison_df

metrics = ["Accuracy", "Precision", "Recall", "F1_score"]

plot_df = comparison_df.set_index("Model")[metrics]

plt.figure(figsize=(10, 6))
plot_df.plot(kind="bar", figsize=(10, 6))

plt.title("Random Forest vs LSTM NDVI Baseline Comparison")
plt.ylabel("Score")
plt.xlabel("Model")
plt.ylim(0, 1)
plt.xticks(rotation=20, ha="right")
plt.grid(axis="y")

plt.tight_layout()
plt.savefig("rf_vs_lstm_model_comparison.png", dpi=300, bbox_inches="tight")
plt.show()

files.download("rf_vs_lstm_model_comparison.csv")
files.download("rf_vs_lstm_model_comparison.png")

